# Generated by Django 6.0.2 on 2026-02-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai', models.CharField(max_length=255)),
                ('french', models.CharField(max_length=255)),
                ('vector', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=100)),
                ('quiz_type', models.CharField(choices=[('fr2th', 'French to Thai'), ('th2fr', 'Thai to French'), ('audio', 'Audio'), ('sentence', 'Sentence Completion')], max_length=20)),
                ('result', models.CharField(choices=[('fail', 'False'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=20)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_app.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('cluster_label', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('flashcard_infos', models.JSONField(default=dict)),
                ('is_favorite', models.BooleanField(default=False)),
                ('srs_level', models.IntegerField(default=0)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_app.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
