# Generated by Django 4.2.24 on 2026-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordinfo',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
